ITEM.name = "Граната"
ITEM.description = "Зеленая, потертая, но с чекой. Кидая гранату помни, ее взрыв должен убить еще кого-то, помимо тебя."
ITEM.model = "models/weapons/w_grenade.mdl"
ITEM.class = "weapon_frag"
ITEM.weaponCategory = "grenade"
ITEM.classes = {CLASS_EOW}
ITEM.flag = "V"
ITEM.width = 1
ITEM.height = 1