local PLUGIN = PLUGIN

PLUGIN.name = "Overwatch Voices Xtra Chedder"
PLUGIN.author = "Umbree"
PLUGIN.description = "Adds extra cheesy 3650 voice lines and what not."
PLUGIN.schema = "HL2 RP"
PLUGIN.license = [[
Copyright 2019-2020 DevAppeared

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-- thanks lad; Umbe]]

local function CheckForFemal( client )
	local Char = client:GetCharacter()
	local Desc = Char:GetDescription()
	local FemaleStart, FemaleEnd = string.find( Desc:lower(), "female" )
	local CharFeml = false
	if FemaleStart then
		CharFeml = true
	else
		if client:IsFemale() then
			CharFeml = true
		else
			CharFeml = false
		end
	end
	if CharFeml then
		return CharFeml
	end
	
	return false
end

Schema.voices.Add("Overwatch", "0", "Zero.", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("Overwatch", "1", "One.", "npc/metropolice/vo/one.wav")
Schema.voices.Add("Overwatch", "10", "Ten.", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("Overwatch", "10-0 HUNTING", "10-0, 10-0, viscerator is hunting!", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
Schema.voices.Add("Overwatch", "100", "One-hundred.", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("Overwatch", "10-103 TAG", "Possible 10-103, my location, alert TAG units.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
Schema.voices.Add("Overwatch", "10-107", "I have a 10-107 here, send AirWatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
Schema.voices.Add("Overwatch", "10-108", "We have a 10-108!", "npc/metropolice/vo/wehavea10-108.wav")
Schema.voices.Add("Overwatch", "10-14", "Holding on 10-14 duty, eh, code four.", "npc/metropolice/vo/holdingon10-14duty.wav")
Schema.voices.Add("Overwatch", "10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav")
Schema.voices.Add("Overwatch", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("Overwatch", "10-25", "Any unit, report in with 10-25 as suspect.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
Schema.voices.Add("Overwatch", "10-30", "I have a 10-30, my 10-20, responding, code two.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav")
Schema.voices.Add("Overwatch", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("Overwatch", "10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav")
Schema.voices.Add("Overwatch", "10-78", "Dispatch, I need 10-78, officer in trouble!", "npc/metropolice/vo/dispatchIneed10-78.wav")
Schema.voices.Add("Overwatch", "10-8 standing by", "10-8, standing by.", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("Overwatch", "10-8", "Unit is on-duty, 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav")
Schema.voices.Add("Overwatch", "10-91D", "10-91d count is...", "npc/metropolice/vo/ten91dcountis.wav")
Schema.voices.Add("Overwatch", "10-97 GOA", "10-97, that suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav")
Schema.voices.Add("Overwatch", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
Schema.voices.Add("Overwatch", "10-99", "Officer down, I am 10-99, I repeat, I am 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav")
Schema.voices.Add("Overwatch", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
Schema.voices.Add("Overwatch", "11-6", "Suspect 11-6, my 10-20 is...", "npc/metropolice/vo/suspect11-6my1020is.wav")
Schema.voices.Add("Overwatch", "11-99", "11-99, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("Overwatch", "2", "Two.", "npc/metropolice/vo/two.wav")
Schema.voices.Add("Overwatch", "20", "Twenty.", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("Overwatch", "200", "Two-hundred.", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("Overwatch", "3", "Three.", "npc/metropolice/vo/three.wav")
Schema.voices.Add("Overwatch", "30", "Thirty.", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("Overwatch", "300", "Three-hundred.", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("Overwatch", "34S AT", "All units, BOL, we have 34-S at...", "npc/metropolice/vo/allunitsbol34sat.wav")
Schema.voices.Add("Overwatch", "4", "Four.", "npc/metropolice/vo/four.wav")
Schema.voices.Add("Overwatch", "40", "Fourty.", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("Overwatch", "404", "404 zone.", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("Overwatch", "408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
Schema.voices.Add("Overwatch", "415B", "Is 415b.", "npc/metropolice/vo/is415b.wav")
Schema.voices.Add("Overwatch", "5", "Five.", "npc/metropolice/vo/five.wav")
Schema.voices.Add("Overwatch", "50", "Fifty.", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("Overwatch", "505", "Dispatch, we need AirWatch, subject is 505!", "npc/metropolice/vo/airwatchsubjectis505.wav")
Schema.voices.Add("Overwatch", "6", "Six.", "npc/metropolice/vo/six.wav")
Schema.voices.Add("Overwatch", "60", "Sixty.", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("Overwatch", "603", "603, unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav")
Schema.voices.Add("Overwatch", "63", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
Schema.voices.Add("Overwatch", "7", "Seven.", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("Overwatch", "70", "Seventy.", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("Overwatch", "8", "Eight.", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("Overwatch", "80", "Eighty.", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("Overwatch", "9", "Nine.", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("Overwatch", "90", "Ninety.", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("Overwatch", "THAT'S A GRENADE", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav")
Schema.voices.Add("Overwatch", "ACQUIRING", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav")
Schema.voices.Add("Overwatch", "ADMINISTER", "Administer.", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("Overwatch", "CONFIRMED ADW", "Confirmed as ADW on that suspect, 10-0.", "npc/metropolice/vo/confirmadw.wav")
Schema.voices.Add("Overwatch", "AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("Overwatch", "ALL UNITS MOVE", "All units, move in!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("Overwatch", "AMPUTATE", "Amputate.", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("Overwatch", "ANTICITIZEN", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("Overwatch", "ANTISEPTIC", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav")
Schema.voices.Add("Overwatch", "APEX", "Apex.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("Overwatch", "APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("Overwatch", "ARREST POSITIONS", "All units, move to arrest positions!", "npc/metropolice/vo/movetoarrestpositions.wav")
Schema.voices.Add("Overwatch", "AT CHECKPOINT", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("Overwatch", "AT LOCATION REPORT", "Protection-teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("Overwatch", "BACK ME UP", "Back me up, I'm out!", "npc/metropolice/vo/backmeupImout.wav")
Schema.voices.Add("Overwatch", "BACKUP", "Backup!", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("Overwatch", "BLADE", "Blade.", "npc/combine_soldier/vo/blade.wav")
Schema.voices.Add("Overwatch", "BLEEDING", "Suspect is bleeding from multiple wounds!", "npc/metropolice/vo/suspectisbleeding.wav")
Schema.voices.Add("Overwatch", "BLIP", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("Overwatch", "BLOCK HOLDING", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav")
Schema.voices.Add("Overwatch", "BLOCK", "Block!", "npc/metropolice/vo/block.wav")
Schema.voices.Add("Overwatch", "BOL 243", "CP, we need AirWatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
Schema.voices.Add("Overwatch", "BOOMER", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("Overwatch", "BREAK COVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("Overwatch", "CAN1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("Overwatch", "CAN2", "Pick up the can!", "npc/metropolice/vo/pickupthecan2.wav")
Schema.voices.Add("Overwatch", "CAN3", "I said, pick up the can!", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("Overwatch", "CAN4", "Now, put it in the trash-can.", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("Overwatch", "CAN5", "I said, put it in the trash-can!", "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("Overwatch", "CAN6", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav")
Schema.voices.Add("Overwatch", "CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("Overwatch", "CANALBLOCK", "Canalblock!", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("Overwatch", "CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("Overwatch", "CHECK MISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("Overwatch", "CHECKPOINTS", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav")
Schema.voices.Add("Overwatch", "CITIZEN SUMMONED", "Reporting citizen summoned into voluntary conscription for channel open service detail T94-332.", "npc/metropolice/vo/citizensummoned.wav")
Schema.voices.Add("Overwatch", "CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("Overwatch", "CLASSIFY DB", "Classify subject name as 'DB'; this block ready for clean-out.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
Schema.voices.Add("Overwatch", "CLEANED", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav")
Schema.voices.Add("Overwatch", "CLEAR CODE 100", "Clear and code one-hundred.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("Overwatch", "CLOSE ON SUSPECT", "All units, close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("Overwatch", "CLOSING", "Closing!", {"npc/combine_soldier/vo/closing.wav", "npc/combine_soldier/vo/closing2.wav"})
Schema.voices.Add("Overwatch", "CODE 100", "Code one-hundred.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("Overwatch", "CODE 2", "All units, code two!", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("Overwatch", "CODE 3", "Officer down, request all units, code three to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
Schema.voices.Add("Overwatch", "CODE 7", "Code seven.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("Overwatch", "CONDEMNED", "Condemned zone!", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("Overwatch", "CONTACT 243", "Contact with 243 suspect, my 10-20 is...", "npc/metropolice/vo/contactwith243suspect.wav")
Schema.voices.Add("Overwatch", "CONTACT PRIORITY", "I have contact with a priority two!", "npc/metropolice/vo/contactwithpriority2.wav")
Schema.voices.Add("Overwatch", "CONTACT", "Contact!", "npc/combine_soldier/vo/contact.wav")
Schema.voices.Add("Overwatch", "CONTAINED", "Contained.", "npc/combine_soldier/vo/contained.wav")
Schema.voices.Add("Overwatch", "CONTROL 100", "Control is one-hundred percent this location, no sign of that 647-E.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("Overwatch", "CONTROLSECTION", "Control-section!", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("Overwatch", "CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
Schema.voices.Add("Overwatch", "COPY THAT", "Copy that.", "npc/combine_soldier/vo/copythat.wav")
Schema.voices.Add("Overwatch", "COPY", "Copy.", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("Overwatch", "COVER", "Cover!", "npc/combine_soldier/vo/coverhurt.wav")
Schema.voices.Add("Overwatch", "CP COMPROMISED", "CP is compromised, re-establish!", "npc/metropolice/vo/cpiscompromised.wav")
Schema.voices.Add("Overwatch", "CP ESTABLISH", "CP, we need to establish our perimeter at...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
Schema.voices.Add("Overwatch", "CP OVERRUN", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
Schema.voices.Add("Overwatch", "DAGGER", "Dagger.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("Overwatch", "DASH", "Dash.", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("Overwatch", "DB COUNT", "DB count is...", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("Overwatch", "DEFENDER", "Defender!", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("Overwatch", "DESERVICED AREA", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("Overwatch", "DESIGNATE SUSPECT", "Designate suspect as...", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("Overwatch", "DESTROY COVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("Overwatch", "DISLOCATE INTERPOSE", "Fire to dislocate that interpose!", "npc/metropolice/vo/firetodislocateinterpose.wav")
Schema.voices.Add("Overwatch", "DISMOUNTING HARDPOINT", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("Overwatch", "DISP APB", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav")
Schema.voices.Add("Overwatch", "DISTRIBUTION BLOCK", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("Overwatch", "DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("Overwatch", "DONT MOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("Overwatch", "ECHO", "Echo.", "npc/combine_soldier/vo/echo.wav")
Schema.voices.Add("Overwatch", "ENGAGING", "Engaging!", "npc/combine_soldier/vo/engaging.wav")
Schema.voices.Add("Overwatch", "ESTABLISH NEW CP", "Fall down, establish a new CP!", "npc/metropolice/vo/establishnewcp.wav")
Schema.voices.Add("Overwatch", "EXPOSE TARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("Overwatch", "EXTERNAL", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
Schema.voices.Add("Overwatch", "FINAL VERDICT", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("Overwatch", "FINAL WARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("Overwatch", "FIRST WARNING", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("Overwatch", "FIST", "Fist.", "npc/combine_soldier/vo/fist.wav")
Schema.voices.Add("Overwatch", "FLASH", "Flash.", "npc/combine_soldier/vo/flash.wav")
Schema.voices.Add("Overwatch", "FLATLINE", "Flatline.", "npc/combine_soldier/vo/flatline.wav")
Schema.voices.Add("Overwatch", "FLUSH", "Flush.", "npc/combine_soldier/vo/flush.wav")
Schema.voices.Add("Overwatch", "FREE NECROTICS", "I have free necrotics!", "npc/metropolice/vo/freenecrotics.wav")
Schema.voices.Add("Overwatch", "GET DOWN", "Get down!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("Overwatch", "GET OUT", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("Overwatch", "GETTING 647E", "Still getting that 647-E from local surveillance.", "npc/metropolice/vo/stillgetting647e.wav")
Schema.voices.Add("Overwatch", "GHOST", "Ghost.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("Overwatch", "GO AGAIN", "PT, go again.", "npc/metropolice/vo/ptgoagain.wav")
Schema.voices.Add("Overwatch", "GO SHARP", "Go sharp!", "npc/combine_soldier/vo/gosharp.wav")
Schema.voices.Add("Overwatch", "GOING IN", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("Overwatch", "GOT A DB", "Uh, we got a DB here, cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
Schema.voices.Add("Overwatch", "GOT HIM AGAIN", "Got him again, suspect is 10-20 at...", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
Schema.voices.Add("Overwatch", "GOT ONE ACCOMPLICE", "I got one accomplice here!", "npc/metropolice/vo/gotoneaccomplicehere.wav")
Schema.voices.Add("Overwatch", "GOT SUSPECT ONE", "I got suspect one here!", "npc/metropolice/vo/gotsuspect1here.wav")
Schema.voices.Add("Overwatch", "GRENADE", "Grenade!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("Overwatch", "GRID", "Grid.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("Overwatch", "HAHA", "Haha.", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("Overwatch", "HAMMER", "Hammer.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("Overwatch", "HARDPOINT PROSECUTE", "Is at hardpoint, ready to prosecute!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
Schema.voices.Add("Overwatch", "HARDPOINT SCANNING", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav")
Schema.voices.Add("Overwatch", "HELIX", "Helix.", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("Overwatch", "HELP", "Help!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("Overwatch", "HERO", "Hero!", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("Overwatch", "HES 148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav")
Schema.voices.Add("Overwatch", "HIGH PRIORITY", "High-priority region.", "npc/metropolice/vo/highpriorityregion.wav")
Schema.voices.Add("Overwatch", "HOLD IT", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("Overwatch", "HOLD POSITION", "Protection-team, hold this position.", "npc/metropolice/vo/holdthisposition.wav")
Schema.voices.Add("Overwatch", "HOLD", "Hold it!", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("Overwatch", "HUNTER", "Hunter.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("Overwatch", "HURRICANE", "Hurricane.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("Overwatch", "I SAID MOVE", "I said move along.", "npc/metropolice/vo/Isaidmovealong.wav")
Schema.voices.Add("Overwatch", "ICE", "Ice.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("Overwatch", "IN POSITION", "In position.", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("Overwatch", "INBOUND", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("Overwatch", "INFECTED", "Infected.", "npc/combine_soldier/vo/infected.wav")
Schema.voices.Add("Overwatch", "INFECTION", "Infection!", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("Overwatch", "INFESTED", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("Overwatch", "INJECT", "Inject!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("Overwatch", "INOCULATE", "Inoculate.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("Overwatch", "INTERCEDE", "Intercede!", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("Overwatch", "INTERLOCK", "Interlock!", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("Overwatch", "INVESTIGATE", "Investigate.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("Overwatch", "INVESTIGATING", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav")
Schema.voices.Add("Overwatch", "ION", "Ion.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("Overwatch", "IS 10-108", "Is 10-108!", "npc/metropolice/vo/is10-108.wav")
Schema.voices.Add("Overwatch", "IS 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("Overwatch", "IS CLOSING", "Is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav")
Schema.voices.Add("Overwatch", "IS DOWN", "Is down!", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("Overwatch", "IS INBOUND", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav")
Schema.voices.Add("Overwatch", "IS MOVING IN", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav")
Schema.voices.Add("Overwatch", "IS MOVING", "Is moving in!", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("Overwatch", "IS PASSIVE", "Is passive.", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("Overwatch", "IS READY TO GO", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("Overwatch", "ISOLATE", "Isolate!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("Overwatch", "JET", "Jet.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("Overwatch", "JUDGE", "Judge.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("Overwatch", "JUDGMENT", "Suspect, prepare to receive civil judgment!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("Overwatch", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("Overwatch", "JURY", "Jury!", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("Overwatch", "KEEP MOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("Overwatch", "KILO", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("Overwatch", "KING", "King!", "npc/metropolice/vo/king.wav")
Schema.voices.Add("Overwatch", "LAST SEEN AT", "Hiding, last seen at range...", "npc/metropolice/vo/hidinglastseenatrange.wav")
Schema.voices.Add("Overwatch", "LEADER", "Leader.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("Overwatch", "LEVEL 3", "I have a level three civil-privacy violator here!", "npc/metropolice/vo/level3civilprivacyviolator.wav")
Schema.voices.Add("Overwatch", "LINE", "Line!", "npc/metropolice/vo/line.wav")
Schema.voices.Add("Overwatch", "LOCATION", "Location?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("Overwatch", "LOCK POSITION", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav")
Schema.voices.Add("Overwatch", "LOCK", "Lock!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("Overwatch", "LOOK OUT", "Look out!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("Overwatch", "LOOSE PARASITICS", "Loose parasitics!", "npc/metropolice/vo/looseparasitics.wav")
Schema.voices.Add("Overwatch", "LOST CONTACT", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav")
Schema.voices.Add("Overwatch", "LOW ON", "Running low on verdicts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav")
Schema.voices.Add("Overwatch", "MACE", "Mace.", "npc/combine_soldier/vo/mace.wav")
Schema.voices.Add("Overwatch", "MAINTAIN CP", "All units, maintain this CP!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("Overwatch", "MALCOMPLIANCE", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
Schema.voices.Add("Overwatch", "MALCOMPLIANT 10-107", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
Schema.voices.Add("Overwatch", "MALIGNANT", "Malignant!", "npc/metropolice/vo/malignant.wav")
Schema.voices.Add("Overwatch", "MATCH ON APB", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav")
Schema.voices.Add("Overwatch", "MINOR HITS", "Minor hits, continuing prosecution!", "npc/metropolice/vo/minorhitscontinuing.wav")
Schema.voices.Add("Overwatch", "MOVE ALONG", "Move along!", "npc/metropolice/vo/movealong.wav")
Schema.voices.Add("Overwatch", "MOVE BACK", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("Overwatch", "MOVE IN", "Move in!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("Overwatch", "MOVE IT", "Move it!", "npc/metropolice/vo/moveit.wav")
Schema.voices.Add("Overwatch", "MOVE", "Move!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("Overwatch", "MOVING TO COVER", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("Overwatch", "MOVING TO HARDPOINT", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("Overwatch", "NECROTICS", "Necrotics!", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("Overwatch", "NEED ANY HELP", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("Overwatch", "NEEDS ASSISTANCE", "Officer needs assistance, I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
Schema.voices.Add("Overwatch", "NEEDS HELP", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
Schema.voices.Add("Overwatch", "NO 647", "Clear, no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
Schema.voices.Add("Overwatch", "NO CONTACT", "No contact!", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("Overwatch", "NO I'M GOOD", "No, I'm good.", "vo/trainyard/ba_noimgood.wav")
Schema.voices.Add("Overwatch", "NO VISUAL ON", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav")
Schema.voices.Add("Overwatch", "NOMAD", "Nomad.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("Overwatch", "NONCITIZEN", "Noncitizen.", "npc/metropolice/vo/noncitizen.wav")
Schema.voices.Add("Overwatch", "NONPATROL", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("Overwatch", "NONTAGGED VIROMES", "Non-tagged viromes here!", "npc/metropolice/vo/non-taggedviromeshere.wav")
Schema.voices.Add("Overwatch", "NOVA", "Nova.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("Overwatch", "NOW GET OUT", "Now, get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav")
Schema.voices.Add("Overwatch", "NOW", "Now.", "vo/trainyard/ba_thatbeer01.wav")
Schema.voices.Add("Overwatch", "OUTBREAK", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav")
Schema.voices.Add("Overwatch", "OUTBREAK", "Outbreak!", "npc/metropolice/vo/outbreak.wav")
Schema.voices.Add("Overwatch", "OVERWATCH", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("Overwatch", "PACIFYING", "Pacifying!", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("Overwatch", "PAIN1", "Ugh!", "npc/metropolice/pain1.wav")
Schema.voices.Add("Overwatch", "PAIN2", "Uagh!", "npc/metropolice/pain2.wav")
Schema.voices.Add("Overwatch", "PAIN3", "Augh!", "npc/metropolice/pain3.wav")
Schema.voices.Add("Overwatch", "PAIN4", "Agh!", "npc/metropolice/pain4.wav")
Schema.voices.Add("Overwatch", "PATROL", "Patrol!", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("Overwatch", "PAYBACK", "Payback.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("Overwatch", "PHANTOM", "Phantom.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("Overwatch", "PICKUP 647E", "Anyone else pick up a, uh... 647-E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("Overwatch", "POSITION AT HARDPOINT", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("Overwatch", "POSITION TO CONTAIN", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav")
Schema.voices.Add("Overwatch", "POSSIBLE 404", "Possible 404 here!", "npc/metropolice/vo/possible404here.wav")
Schema.voices.Add("Overwatch", "POSSIBLE 647E", "Possible 647-E here, request AirWatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav")
Schema.voices.Add("Overwatch", "POSSIBLE ACCOMPLICE", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
Schema.voices.Add("Overwatch", "POSSIBLE LEVEL 3", "Possible level three civil-privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
Schema.voices.Add("Overwatch", "PREPARING TO JUDGE", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav")
Schema.voices.Add("Overwatch", "PRESERVE", "Preserve!", "npc/metropolice/vo/preserve.wav")
Schema.voices.Add("Overwatch", "PRESSURE", "Pressure!", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("Overwatch", "PRIORITY 1", "Confirm, priority-one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav")
Schema.voices.Add("Overwatch", "PRIORITY 2", "I have a priority-two anti-citizen here!", "npc/metropolice/vo/priority2anticitizenhere.wav")
Schema.voices.Add("Overwatch", "PRODUCTION BLOCK", "Production-block.", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("Overwatch", "PROSECUTE MALCOMPLIANT", "Ready to prosecute malcompliant citizen, final warning issued!", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
Schema.voices.Add("Overwatch", "PROSECUTE", "Prosecute!", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("Overwatch", "PROSECUTING", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav")
Schema.voices.Add("Overwatch", "PROTECTION COMPLETE", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("Overwatch", "QUICK", "Quick!", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("Overwatch", "QUICKSAND", "Quicksand.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("Overwatch", "RANGE", "Range.", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("Overwatch", "RANGER", "Ranger.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("Overwatch", "RAZOR", "Razor.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("Overwatch", "READY AMPUTATE", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("Overwatch", "READY CHARGES", "Ready charges!", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("Overwatch", "READY JUDGE", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("Overwatch", "READY PROSECUTE", "Ready to prosecute!", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("Overwatch", "READY WEAPONS", "Ready weapons!", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("Overwatch", "REAPER", "Reaper.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("Overwatch", "REINFORCEMENT TEAMS", "Reinforcement-teams, code three!", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("Overwatch", "REPORT CLEAR", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("Overwatch", "REPORT IN", "CP requests all units, uhh... Location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
Schema.voices.Add("Overwatch", "REPORT LOCATION", "All units, report location suspect!", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("Overwatch", "REPORT STATUS", "Local CP-teams, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("Overwatch", "REPURPOSED", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("Overwatch", "RESIDENTIAL BLOCK", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("Overwatch", "RESPOND CODE 3", "All units at location, responding code three!", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("Overwatch", "RESPONDING", "Responding.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("Overwatch", "RESTRICT", "Restrict!", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("Overwatch", "RESTRICTED", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("Overwatch", "RESTRICTION ZONE", "Terminal restriction-zone!", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("Overwatch", "RIPCORD", "Ripcord!", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("Overwatch", "RODGER THAT", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("Overwatch", "ROLLER", "Roller!", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("Overwatch", "RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("Overwatch", "SACRIFICE CODE", "All units, sacrifice code one and maintain this CP!", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
Schema.voices.Add("Overwatch", "SAVAGE", "Savage.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("Overwatch", "SCAR", "Scar.", "npc/combine_soldier/vo/scar.wav")
Schema.voices.Add("Overwatch", "SEARCH", "Search!", "npc/metropolice/vo/search.wav")
Schema.voices.Add("Overwatch", "SEARCHING FOR SUSPECT", "Searching for suspect.", "npc/metropolice/vo/searchingforsuspect.wav")
Schema.voices.Add("Overwatch", "SECOND WARNING", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("Overwatch", "SECTOR NOT STERILE", "Confirmed- sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
Schema.voices.Add("Overwatch", "SECTOR NOT SECURE", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("Overwatch", "SECURE ADVANCE", "Assault-point secured, advance!", "npc/metropolice/vo/assaultpointsecureadvance.wav")
Schema.voices.Add("Overwatch", "SECURE", "Secure.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("Overwatch", "SENTENCE", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav")
Schema.voices.Add("Overwatch", "SERVE", "Serve.", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("Overwatch", "SHADOW", "Shadow.", "npc/combine_soldier/vo/shadow.wav")
Schema.voices.Add("Overwatch", "SHARPZONE", "Sharpzone.", "npc/combine_soldier/vo/sharpzone.wav")
Schema.voices.Add("Overwatch", "SHIT", "Shit!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("Overwatch", "SHOTS FIRED", "Shots fired, hostile malignants here!", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
Schema.voices.Add("Overwatch", "SLAM", "Slam.", "npc/combine_soldier/vo/slam.wav")
Schema.voices.Add("Overwatch", "SLASH", "Slash.", "npc/combine_soldier/vo/slash.wav")
Schema.voices.Add("Overwatch", "SOCIOCIDE", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("Overwatch", "SOCIOSTABLE", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("Overwatch", "SPEAR", "Spear.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("Overwatch", "STAB", "Stab.", "npc/combine_soldier/vo/stab.wav")
Schema.voices.Add("Overwatch", "STANDING BY", "Standing by.", "npc/combine_soldier/vo/standingby].wav")
Schema.voices.Add("Overwatch", "STAR", "Star.", "npc/combine_soldier/vo/star.wav")
Schema.voices.Add("Overwatch", "STATIONBLOCK", "Stationblock.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("Overwatch", "STAY ALERT", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav")
Schema.voices.Add("Overwatch", "STERILIZE", "Sterilize!", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("Overwatch", "STINGER", "Stinger.", "npc/combine_soldier/vo/stinger.wav")
Schema.voices.Add("Overwatch", "STORM", "Storm.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("Overwatch", "STRIKE", "Striker.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("Overwatch", "SUBJECT 505", "Subject is 505!", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("Overwatch", "SUBJECT HIGH SPEED", "All units, be advised, subject is now high-speed!", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("Overwatch", "SUBJECT", "Subject!", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("Overwatch", "SUNDOWN", "Sundown.", "npc/combine_soldier/vo/sundown.wav")
Schema.voices.Add("Overwatch", "SUSPECT INCURSION", "Disp reports suspect-incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
Schema.voices.Add("Overwatch", "SUSPECT MOVED TO", "Suspect has moved now to...", "npc/metropolice/vo/supsecthasmovednowto.wav")
Schema.voices.Add("Overwatch", "SUSPECT RESTRICTED CANALS", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
Schema.voices.Add("Overwatch", "SUSPEND", "Suspend!", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("Overwatch", "SWEEPER", "Sweeper.", "npc/combine_soldier/vo/sweeper.wav")
Schema.voices.Add("Overwatch", "SWEEPING IN", "Sweeping in!", "npc/combine_soldier/vo/sweepingin.wav")
Schema.voices.Add("Overwatch", "SWEEPING SUSPECT", "Sweeping for suspect!", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("Overwatch", "SWIFT", "Swift.", "npc/combine_soldier/vo/swift.wav")
Schema.voices.Add("Overwatch", "SWORD", "Sword.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("Overwatch", "TAG 10-91D", "Tag 10-91d!", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("Overwatch", "TAG BUG", "Tag one bug!", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("Overwatch", "TAG NECROTIC", "Tag one necrotic!", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("Overwatch", "TAG PARASITIC", "Tag one parasitic!", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("Overwatch", "TAKE A LOOK", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("Overwatch", "TAKE COVER", "Take cover!", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("Overwatch", "TAP", "Tap!", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("Overwatch", "TARGET", "Target.", "npc/combine_soldier/vo/target.wav")
Schema.voices.Add("Overwatch", "TEAM ADVANCE", "Team in position, advance!", "npc/metropolice/vo/teaminpositionadvance.wav")
Schema.voices.Add("Overwatch", "TEAM HOLDING", "Stabilization team holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
Schema.voices.Add("Overwatch", "THERE HE GOES", "There he goes! He's at...", "npc/metropolice/vo/therehegoeshesat.wav")
Schema.voices.Add("Overwatch", "THERE HE IS", "There he is!", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("Overwatch", "TRACKER", "Tracker.", "npc/combine_soldier/vo/tracker.wav")
Schema.voices.Add("Overwatch", "TRANSITBLOCK", "Transit-block.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("Overwatch", "TROUBLE", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("Overwatch", "UNDER FIRE", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
Schema.voices.Add("Overwatch", "UNIFORM", "Uniform.", "npc/combine_soldier/vo/uniform.wav")
Schema.voices.Add("Overwatch", "UNION", "Union!", "npc/metropolice/vo/union.wav")
Schema.voices.Add("Overwatch", "UNKNOWN", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav")
Schema.voices.Add("Overwatch", "UP THERE", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("Overwatch", "UPI", "UPI.", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("Overwatch", "UTL SUSPECT", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav")
Schema.voices.Add("Overwatch", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("Overwatch", "VACATE", "Vacate, citizen!", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("Overwatch", "VAMP", "Vamp.", "npc/combine_soldier/vo/vamp.wav")
Schema.voices.Add("Overwatch", "VERDICT", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
Schema.voices.Add("Overwatch", "VICE", "Vice!", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("Overwatch", "VICTOR", "Victor!", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("Overwatch", "VISCON", "Viscon.", "npc/combine_soldier/vo/viscon.wav")
Schema.voices.Add("Overwatch", "VISUAL EXOGEN", "Visual on exogen.", "npc/combine_soldier/vo/visualonexogens.wav")
Schema.voices.Add("Overwatch", "WARNING GIVEN", "Second warning given!", "npc/metropolice/vo/secondwarning.wav")
Schema.voices.Add("Overwatch", "WASTERIVER", "Wasteriver.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("Overwatch", "WATCH IT", "Watch it!", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("Overwatch", "WINDER", "Winder.", "npc/combine_soldier/vo/winder.wav")
Schema.voices.Add("Overwatch", "WORKFORCE", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("Overwatch", "WRAP IT UP", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("Overwatch", "XRAY", "XRay!", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("Overwatch", "YELLOW", "Yellow!", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("Overwatch", "YOU CAN GO", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("Overwatch", "ZONE", "Zone!", "npc/metropolice/vo/zone.wav")

Schema.voices.AddClass("Overwatch", function(client)
	return ( client:IsCombine() and ( not CheckForFemal( client ) ) )
end)
--[[
-- Assasin --
	-- Friendly Fire --
	Schema.voices.Add("Assasin", "Friendly Fire1", "Watch your damn sights! Moron.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/friendlyfire/park_rad_ff_01.wav")
	Schema.voices.Add("Assasin", "Friendly Fire2", "Check your damn targets!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/friendlyfire/park_rad_ff_02.wav")
	Schema.voices.Add("Assasin", "Whats your problem", "Whats your problem?", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/friendlyfire/park_rad_ff_03.wav")
	Schema.voices.Add("Assasin", "Friendly Fire3", "Hey! Check your targets.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/friendlyfire/park_rad_ff_04.wav")
	Schema.voices.Add("Assasin", "Friendly Fire4", "Watch your target ID!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/friendlyfire/park_rad_ff_05.wav")
	-- Good Job --
	Schema.voices.Add("Assasin", "Nice work", "Nice work.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/goodjob/park_rad_goodjob_01.wav")
	Schema.voices.Add("Assasin", "Job Well done", "Job well done.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/goodjob/park_rad_goodjob_02.wav")
	Schema.voices.Add("Assasin", "That was great", "That was great.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/goodjob/park_rad_goodjob_03.wav")
	Schema.voices.Add("Assasin", "Not bad at all", "Not bad at all.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/goodjob/park_rad_goodjob_04.wav")
	-- grenade --
	Schema.voices.Add("Assasin", "Grenade", "Grenade!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/grenadein/park_rad_greninc_01.wav")
	Schema.voices.Add("Assasin", "frag", "Heads up, frag!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/grenadein/park_rad_greninc_02.wav")
	Schema.voices.Add("Assasin", "Grenade2", "Incoming grenade!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/grenadein/park_rad_greninc_03.wav")
	Schema.voices.Add("Assasin", "frag2", "Hostile frag grenade!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/grenadein/park_rad_greninc_04.wav")
	-- Hello --
	Schema.voices.Add("Assasin", "Hello", "Hello.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/hello/park_rad_hello_01.wav")
	Schema.voices.Add("Assasin", "Hello2", "Hello there.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/hello/park_rad_hello_02.wav")
	Schema.voices.Add("Assasin", "Good to see you", "Good to see you.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/hello/park_rad_hello_03.wav")
	Schema.voices.Add("Assasin", "How are you", "Hows everything going?", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/hello/park_rad_hello_04.wav")
	-- help me --
	Schema.voices.Add("Assasin", "help", "Need an assist.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/helpme/park_rad_helpme_01.wav")
	Schema.voices.Add("Assasin", "help2", "Assist me.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/helpme/park_rad_helpme_02.wav")
	Schema.voices.Add("Assasin", "help3", "I need a hand here.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/helpme/park_rad_helpme_03.wav")
	Schema.voices.Add("Assasin", "help4", "Assist on me.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/helpme/park_rad_helpme_03.wav")
	-- Sorrysimp --
	Schema.voices.Add("Assasin", "Sorry", "Sorry.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/sorrysimp/park_rad_sorry_01.wav")
	Schema.voices.Add("Assasin", "Sorry2", "I'm sorry, my bad.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/sorrysimp/park_rad_sorry_02.wav")
	Schema.voices.Add("Assasin", "Sorry3", "I didn't mean to do that.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/sorrysimp/park_rad_sorry_03.wav")
	Schema.voices.Add("Assasin", "Sorry4", "Apologies, not what I intended.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/sorrysimp/park_rad_sorry_04.wav")
	-- taunt --
	Schema.voices.Add("Assasin", "taunt1", "I am going to enjoy taking you apart.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/taunt/park_rad_taunt_01.wav")
	Schema.voices.Add("Assasin", "taunt2", "Settle down.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/taunt/park_rad_taunt_02.wav")
	-- thanks --
	Schema.voices.Add("Assasin", "Thanks", "Thanks.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/thankyousimp/park_rad_thanks_01.wav")
	Schema.voices.Add("Assasin", "Thank you", "Thank you.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/thankyousimp/park_rad_thanks_02.wav")
	Schema.voices.Add("Assasin", "my thanks", "My thanks.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/thankyousimp/park_rad_thanks_03.wav")
	Schema.voices.Add("Assasin", "much appreciated", "Much appreciated.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/radial/thankyousimp/park_rad_thanks_04.wav")
	-- friendly killed --
	Schema.voices.Add("Assasin", "Oh fuck", "Oh fuck.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_fri_01.wav")
	Schema.voices.Add("Assasin", "friendly kia", "Friendly KIA.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_fri_02.wav")
	Schema.voices.Add("Assasin", "friendly down", "Oh no, friendly down!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_fri_03.wav")
	Schema.voices.Add("Assasin", "team engagement", "Tac-com, accidental team engagement.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_fri_04.wav")
	-- Kill --
	Schema.voices.Add("Assasin", "Reading KIA", "Reading 1 is KIA.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_01.wav")
	Schema.voices.Add("Assasin", "Shots good", "Shots good.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_02.wav")
	Schema.voices.Add("Assasin", "good effect", "Good effect on target.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_03.wav")
	Schema.voices.Add("Assasin", "thats a kill", "Thats a kill.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_04.wav")
	Schema.voices.Add("Assasin", "threat down", "Threat down.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_05.wav")
	Schema.voices.Add("Assasin", "tango removed", "Tango removed.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_06.wav")
	Schema.voices.Add("Assasin", "target deleted", "Target deleted.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_07.wav")
	Schema.voices.Add("Assasin", "hostile gone", "Hostile gone.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_08.wav")
	Schema.voices.Add("Assasin", "smoked", "Smoked.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_09.wav")
	Schema.voices.Add("Assasin", "Tag and bagged", "Tagged and bagged.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_10.wav")
	Schema.voices.Add("Assasin", "Confirming", "Confirming.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_11.wav")
	Schema.voices.Add("Assasin", "Body dropped", "Body dropped.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_12.wav")
	Schema.voices.Add("Assasin", "kill", "Kill.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_13.wav")
	Schema.voices.Add("Assasin", "Neutralized", "Neutralized.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_14.wav")
	Schema.voices.Add("Assasin", "And stay down", "And stay down.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_15.wav")
	Schema.voices.Add("Assasin", "Enemy is down", "Enemy is down.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_gen_16.wav")
	-- Kill Sniper --
	Schema.voices.Add("Assasin", "long range down", "Enemy long range is down.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_sni_01.wav")
	Schema.voices.Add("Assasin", "Marksman deleted", "Marksman deleted.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_sni_02.wav")
	Schema.voices.Add("Assasin", "snipers down move", "Snipers down, move!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_sni_03.wav")
	Schema.voices.Add("Assasin", "Sharpshooter eliminated", "Sharpshooter eliminated.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/kill/park_kill_sni_04.wav")
	-- no ammo --
	Schema.voices.Add("Assasin", "Gun is dry", "Gun is dry.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/noammo/park_ooa_gen_01.wav")
	Schema.voices.Add("Assasin", "Anyone have ammo", "Anyone have ammo for me?", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/noammo/park_ooa_gen_02.wav")
	-- reloading --
	Schema.voices.Add("Assasin", "New magazine", "Loading new magazine.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/reloading/reloading1.wav")
	Schema.voices.Add("Assasin", "reloading ammo", "Reloading ammo.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/reloading/reloading2.wav")
	Schema.voices.Add("Assasin", "gotta reload", "Gotta reload.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/reloading/reloading3.wav")
	-- Spawn --
	Schema.voices.Add("Assasin", "Park reporting in", "Park reporting in.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spawn/park_spawn_gen_01.wav")
	Schema.voices.Add("Assasin", "Good choice", "Good choice.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spawn/park_spawn_gen_02.wav")
	Schema.voices.Add("Assasin", "Semper", "Semper occultus.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spawn/park_spawn_gen_03.wav")
	Schema.voices.Add("Assasin", "How can I help", "How can I help?", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spawn/park_spawn_gen_04.wav")
	-- spot --
		-- friendly --
		Schema.voices.Add("Assasin", "on your six", "On your six!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_fri_02.wav")
		Schema.voices.Add("Assasin", "on you", "On you, lets hussle.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_fri_03.wav")
		Schema.voices.Add("Assasin", "moving in formation", "Moving in formation.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_fri_04.wav")
		Schema.voices.Add("Assasin", "behind you", "Behind you, keep it tight!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_fri_05.wav")
		Schema.voices.Add("Assasin", "following move", "Following, move move!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_fri_07.wav")
		-- hostile --
		Schema.voices.Add("Assasin", "confirming hostile", "Confirming hostile.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_gen_01.wav")
		Schema.voices.Add("Assasin", "hostile front", "Hostile 12 o'clock.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_gen_03.wav")
		Schema.voices.Add("Assasin", "assaulting target", "Assaulting target.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_gen_09.wav")
		Schema.voices.Add("Assasin", "taking shot", "Taking the shot.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_gen_14.wav")
		Schema.voices.Add("Assasin", "sniper", "Sniper, take cover!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_sni_01.wav")
		Schema.voices.Add("Assasin", "sniper2", "Enemy sniper shooting!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/spot/park_spot_sni_02.wav")
	-- pain --
	Schema.voices.Add("Assasin", "pain1", "Daa!", "CourragCourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_gen_02.wav")
	Schema.voices.Add("Assasin", "pain2", "Errgh!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_gen_03.wav")
	Schema.voices.Add("Assasin", "pain3", "Ermmh!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_gen_05.wav")
	Schema.voices.Add("Assasin", "pain4", "Erugh!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_gen_06.wav")
	Schema.voices.Add("Assasin", "pain5", "Oughf!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_gen_09.wav")
	Schema.voices.Add("Assasin", "taking hits", "Oughf, Taking hits!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_hds_02.wav")
	Schema.voices.Add("Assasin", "damnit", "Damnit!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_hds_03.wav")
	Schema.voices.Add("Assasin", "Underfire", "Urgh, Underfire!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_hds_04.wav")
	Schema.voices.Add("Assasin", "balls", "Balls.", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_hds_05.wav")
	Schema.voices.Add("Assasin", "im hit", "I'm hit!", "CourragatedDawn/Xtra/vo/assasinTFAVOX/helenpark/pain/park_pain_hds_06.wav")
-- end --

Schema.voices.AddClass("Assasin", function(client)
	return ( client:IsCombine() )
end)
]]--
-- heavy synth --
	-- Alert --
	Schema.voices.Add("HeavySynth", "Alert", "⋥∣⊊⋊⋙⊣ ∅⊇⋿∊⋺", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_alert1.ogg")
	Schema.voices.Add("HeavySynth", "Alert2", "≤∷⊏≪ ≥∈∽≫⋮≸≷", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_alert2.ogg")
	Schema.voices.Add("HeavySynth", "Alert3", "≤∷⊏≪ ≉≈∲⋅≌⋏∙∦⊎≟⊊", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_alert3.ogg")
	-- Anger --
	Schema.voices.Add("HeavySynth", "Anger", "≦ ⋜≉∏⋃⋷∸∫⋱⋲≑", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_anger1.ogg")
	Schema.voices.Add("HeavySynth", "Anger2", "⋃∐⋟∊≕∏⊙✚∻⋀⋚ ⋙⊣∅⊇⋿∊⋺", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_anger2.ogg")
	-- Scan --
	Schema.voices.Add("HeavySynth", "Scan", "⋁⊴ ∈⊢⋰⊀⊐ ⋁⊴", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_scan1.ogg")
	Schema.voices.Add("HeavySynth", "Scan2", "⋁⊴ ⊻≟∎∺⊳√⊊≑⊇≚∤ ⋁⊴", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_scan2.ogg")
	Schema.voices.Add("HeavySynth", "Scan3", "⋁⊴ ∖∮⊷⋞≂⊿∶⋺≇≷⋈ ⋁⊴", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_scan3.ogg")
	Schema.voices.Add("HeavySynth", "Scan4", "⋁⊴ ⋸≺⋤✖⊃⊻⊟≣⊢∸∸ ⋁⊴", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_scan4.ogg")
	Schema.voices.Add("HeavySynth", "Scan5", "⋁⊴ ≳≢≓∰⊫⋋≰✚⊵⋞⋾ ⋁⊴", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_scan5.ogg")
	Schema.voices.Add("HeavySynth", "Scan6", "⋁⊴ ⊵⋷⊂∆⊊∻⋎≑⊵⋡⊎ ⋁⊴", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_scan6.ogg")
	-- Speech --
	Schema.voices.Add("HeavySynth", "Speech", "∈⋠≹≵⋠∨⊵⋿≗∈⋄⊂∆⊊∻", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_speech1.ogg")
	Schema.voices.Add("HeavySynth", "Speech2", "∈⋠≹≵⋠...", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_speech2.ogg")
	Schema.voices.Add("HeavySynth", "Speech3", "∇⋚≴, ⊝≮⋁, ⊅⊇⊒∑∺", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_speech3.ogg")
	Schema.voices.Add("HeavySynth", "Speech4", "≘≿≢≿✚⊘⋈≡≾∳⋦", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_speech4.ogg")
	Schema.voices.Add("HeavySynth", "Speech5", "⊽⋵∦⊥⊱⊝⊞≋⊍≃⊘", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_speech5.ogg")
	Schema.voices.Add("HeavySynth", "Speech6", "≞∑⋏≱⊻≪∦⊒⊝⊞≋≐⋵≰", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_speech6.ogg")
	Schema.voices.Add("HeavySynth", "Speech7", "⊅⋁⊴⋫≨ ⋷≲∔≍⋒≼≛", "CourragatedDawn/Xtra/npc/HeavySynthSounds/hvy_snt_speech7.ogg")
-- end --

Schema.voices.AddClass("HeavySynth", function(client)
	return ( client:Team() == FACTION_SYNTH )
end)
